// import { serial } from "drizzle-orm/mysql-core";
// import { pgTable } from "drizzle-orm/pg-core";
import { pgTable, PgTable, serial, text, varchar } from "drizzle-orm/pg-core";

export const MockInterview = pgTable('mockInterview', {
  id: serial('id').primaryKey(),
  jsonMockResp: text('jsonMockResp'),
  jobPosition: varchar('jobPosition').notNull(),
  jobDesc: varchar('jobDesc').notNull(),
  jobExperience: varchar('jobExperience').notNull(),
  jobResume: varchar('jobResume'),
  createdBy: varchar('createdBy').notNull(),
  createdAt: varchar('createdAt'),
  timeOfCreation: varchar('timeOfCreation'),
  mockId: varchar('mockId').notNull(),
  options: varchar('options'),
})

export const UserAnswer = pgTable('userAnswer', {

  id: serial('id').primaryKey(),
  mockIdRef: varchar('mockId').notNull(),
  question: varchar('question').notNull(),
  correctAns: text('correctAns'),
  userAns: text('userAns'),
  feedback: text('feedback'),
  rating: varchar('rating'),
  userEmail: varchar('userEmail'),
  createdAt: varchar('createdAt'),
  options: varchar('options'),
  eyeContact: varchar('eyeContact'),
  confidence: varchar('confidence'),

})

export const resumeScore = pgTable('resumeScore', {

  // id: serial('id').primaryKey(),
  // resumeText: varchar('resumeText').notNull(),
  // jobDescription: varchar('jobDescription'),
  // atsScore: varchar('atsScore').notNull(),
  // strength: varchar('strength'),
  // weakness: varchar('weakness'),
  // jobMatching: varchar('jobMatching'),
  // missingKeywords: varchar('missingKeywords'),
  // suggestions: varchar('suggestions'),
  // grammerError: varchar('grammerError'),
  // typosError: varchar('typosError'),
  // spellingMistakes: varchar('spellingMistakes'),
  // experiencedForJob: varchar('experiencedForJob'),

  id: serial('id').primaryKey(), // Auto-incrementing primary key
  resumeText: varchar('resumeText').notNull(), // Extracted text from the resume PDF
  jobDescription: varchar('jobDescription'), // Job description provided by the user
  atsScore: varchar('atsScore').notNull(), // ATS score generated by the AI
  strength: varchar('strength'), // Strengths identified in the resume
  weakness: varchar('weakness'), // Weaknesses identified in the resume
  jobMatching: varchar('jobMatching'), // Job match percentage
  missingKeywords: varchar('missingKeywords'), // Missing keywords in the resume
  suggestions: varchar('suggestions'), // Suggestions for improving the resume
  grammerError: varchar('grammerError'), // Grammar errors in the resume
  typosError: varchar('typosError'), // Typographical errors in the resume
  spellingMistakes: varchar('spellingMistakes'), // Spelling mistakes in the resume
  experiencedForJob: varchar('experiencedForJob'), // Experience relevant to the job

})

export const contactUs = pgTable('contactUs', {

  id: serial('id').primaryKey(),
  name: varchar('userName').notNull(),
  userEmail: varchar('userEmail').notNull(),
  userMessage: varchar('userMessage').notNull(),
})

export const jobMatchScore = pgTable('jobMatchScore', {
  id: serial('id').primaryKey(),          // Auto-increment primary key
  resumeText: text('resumeText'),         // Extracted resume content
  skills: text('skills'),                 // Candidate's provided skills
  matchingProfiles: text('matchingProfiles'), // Matched job profiles
  missingSkills: text('missingSkills'),   // Skills the candidate needs to learn
});
